# データフレームのマージ

通常のKeyを用いたデータのマージ方法の記載をする

In [6]:
import numpy as np
import pandas as pd
from pandas import DataFrame , Series

In [9]:
dframe1 = DataFrame({'key':['x','z','y','z','x','y'], 'dataset_1':np.arange(6)})

In [10]:
dframe1

key  dataset_1
0   x          0
1   z          1
2   y          2
3   z          3
4   x          4
5   y          5

In [11]:
dframe2 = DataFrame({'key' : ['q','y','z'], 'data_set_2':[1,2,5]})
dframe2

key  data_set_2
0   q           1
1   y           2
2   z           5

In [12]:
# データのマージ 何も指定がない場合、同じIndexのkeyをもとにマージを行う
pd.merge(dframe1,dframe2)

key  dataset_1  data_set_2
0   z          1           5
1   z          3           5
2   y          2           2
3   y          5           2

In [13]:
# マージするKeyの指定
pd.merge(dframe1,dframe2,on='key')

key  dataset_1  data_set_2
0   z          1           5
1   z          3           5
2   y          2           2
3   y          5           2

In [14]:
# マージ方法の指定は「how」を使用 leftであれば左側のdframe1を基準とする dframe2で指定したければ'right'にすればよい
pd.merge(dframe1,dframe2,on='key', how='left') #dframe1基準

key  dataset_1  data_set_2
0   x          0         NaN
1   z          1         5.0
2   y          2         2.0
3   z          3         5.0
4   x          4         NaN
5   y          5         2.0

In [15]:
pd.merge(dframe1,dframe2,on='key', how='right') #dframe2基準

key  dataset_1  data_set_2
0   q        NaN           1
1   y        2.0           2
2   y        5.0           2
3   z        1.0           5
4   z        3.0           5

In [16]:
# 今度は多対多
# 両方のDataFrameで、keyに関して複数の行がある。
dframe3 = DataFrame({'key': ['X', 'X', 'X', 'Y', 'Z', 'Z'],
                 'data_set_3': range(6)})
dframe4 = DataFrame({'key': ['Y', 'Y', 'X', 'X', 'Z'],
                 'data_set_4': range(5)})
#マージする。Xに対応するデータが片方は2個、片方は３個あるので、2*3=6個のデータが出力される
pd.merge(dframe3, dframe4)

key  data_set_3  data_set_4
0   X           0           2
1   X           0           3
2   X           1           2
3   X           1           3
4   X           2           2
5   X           2           3
6   Y           3           0
7   Y           3           1
8   Z           4           4
9   Z           5           4

In [17]:
# キーでのマージ手法
df_left = DataFrame({'key1': ['SF', 'SF', 'LA'],
                  'key2': ['one', 'two', 'one'],
                  'left_data': [10,20,30]})
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [18]:
df_right = DataFrame({'key1': ['SF', 'SF', 'LA', 'LA'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'right_data': [40,50,60,70]})
df_right

key1 key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [19]:
# キーでのマージ onでKeyを指定することでキーでのマージが可能 
pd.merge(df_left, df_right, on=['key1', 'key2'], how='outer')

key1 key2  left_data  right_data
0   SF  one       10.0        40.0
1   SF  one       10.0        50.0
2   SF  two       20.0         NaN
3   LA  one       30.0        60.0
4   LA  two        NaN        70.0

In [20]:
# マージ時にキーが重複している場合、接頭辞がくっつく
# 追加する文字列を指定することが可能
pd.merge(df_left,df_right, on='key1',suffixes=('_lefty','_righty'))

key1 key2_lefty  left_data key2_righty  right_data
0   SF        one         10         one          40
1   SF        one         10         one          50
2   SF        two         20         one          40
3   SF        two         20         one          50
4   LA        one         30         one          60
5   LA        one         30         two          70

# Indexを使ったマージ

Indexを使ったマージ方法の記載

In [21]:
import pandas as pd 
import numpy as np 
from pandas import DataFrame

In [22]:
df_left = DataFrame({'key':['X','Y','Z','X','Y'],'data':range(5)})
df_left

key  data
0   X     0
1   Y     1
2   Z     2
3   X     3
4   Y     4

In [23]:
df_right = DataFrame({'group_data':[10,20]},index=['X','Y'])
df_right

group_data
X          10
Y          20

In [24]:
# 通常のIndexを使ったマージ
pd.merge(df_left,df_right,left_on='key',right_index=True)

key  data  group_data
0   X     0          10
3   X     3          10
1   Y     1          20
4   Y     4          20

In [25]:
# 通常のIndexを使ったマージ outer使用
pd.merge(df_left,df_right,left_on='key',right_index=True, how="outer")

key  data  group_data
0   X     0        10.0
3   X     3        10.0
1   Y     1        20.0
4   Y     4        20.0
2   Z     2         NaN

In [26]:
# 階層的なIndexのマージ
df_left_hr = DataFrame({'key1': ['SF','SF','SF','LA','LA'],
                   'key2': [10, 20, 30, 20, 30],
                   'data_set': np.arange(5.)})
df_right_hr = DataFrame(np.arange(10).reshape((5, 2)),
                   index=[['LA','LA','SF','SF','SF'],
                          [20, 10, 10, 10, 20]],
                   columns=['col_1', 'col_2'])

In [27]:
df_left_hr

key1  key2  data_set
0   SF    10       0.0
1   SF    20       1.0
2   SF    30       2.0
3   LA    20       3.0
4   LA    30       4.0

In [28]:
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [29]:
# key1/key2でマージを行う
pd.merge(df_left_hr,df_right_hr,left_on=['key1','key2'],right_index=True)


key1  key2  data_set  col_1  col_2
0   SF    10       0.0      4      5
0   SF    10       0.0      6      7
1   SF    20       1.0      8      9
3   LA    20       3.0      0      1

In [30]:
# joinメソッドでもマージ可能 join: 加える
df_left.join(df_right)


key  data  group_data
0   X     0         NaN
1   Y     1         NaN
2   Z     2         NaN
3   X     3         NaN
4   Y     4         NaN

# データの連結

numpyはnp.concatinateで可能。pandasはconcatで使用する

In [3]:
# 単純な連結
arr1 = np.arange(9).reshape((3,3))
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
# 行方向（axis=0）
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# pandaでの連結
ser1 =  Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])
# concatで、デフォルトは axis=0
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [10]:
# DataFrame版 
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])
pd.concat([dframe1,dframe2]) #Indexが1-3が繰り返されるようなものが作成される

X         Y         Z         Q
0 -0.350497  0.585344 -0.523935       NaN
1  1.413601  0.943389  0.795632       NaN
2 -0.607188  1.130589 -0.453168       NaN
3  0.105427  0.248677  1.014015       NaN
0  0.166073  0.042529       NaN -2.084227
1 -2.532674 -0.926835       NaN  1.710323
2  0.987354  0.317710       NaN -1.535718

In [12]:
# Indexが繰り返ししないようにするパターン Index無視のオプションを有効かする
pd.concat([dframe1,dframe2],ignore_index=True)

X         Y         Z         Q
0 -0.350497  0.585344 -0.523935       NaN
1  1.413601  0.943389  0.795632       NaN
2 -0.607188  1.130589 -0.453168       NaN
3  0.105427  0.248677  1.014015       NaN
4  0.166073  0.042529       NaN -2.084227
5 -2.532674 -0.926835       NaN  1.710323
6  0.987354  0.317710       NaN -1.535718

# データ組み合わせ

別のテーブル同士でNan値を埋め合わせる方法を記載する

In [13]:
# 組み合わせ用のデータ定義
ser1 = Series([2,np.nan,4,np.nan,6,np.nan],
           index=['Q','R','S','T','U','V'])
ser2 = Series(np.arange(len(ser1), dtype=np.float64),
           index=['Q','R','S','T','U','V'])

In [15]:
ser1

Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [16]:
ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [18]:
# np.where(条件, True時のデータ, False時のデータ)でデータを抽出する
np.where(pd.isnull(ser1),ser2,ser1)

array([2., 1., 4., 3., 6., 5.])

In [19]:
# 上述で抽出したデータをpandasのSeriesに入れ込む indexはser1を参照する
Series(np.where(pd.isnull(ser1),ser2,ser1),index=ser1.index)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [20]:
# NULL値を別テーブルの値に置き換える手法2
ser1.combine_first(ser2)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [21]:
# DataFrame版
dframe_odds = DataFrame({'X': [1., np.nan, 3., np.nan],
                     'Y': [np.nan, 5., np.nan, 7.],
                     'Z': [np.nan, 9., np.nan, 11.]})
dframe_evens = DataFrame({'X': [2., 4., np.nan, 6., 8.],
                     'Y': [np.nan, 10., 12., 14., 16.]})

In [22]:
dframe_odds

X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [23]:
dframe_evens

X     Y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [24]:
# Nan値の場合はeven値として埋め込む どちらのテーブルにもない場合はそのままになる
dframe_odds.combine_first(dframe_evens)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN

# Series/DataFrameの変換

stack()/unstack()メソッドで可能。デフォルトではNULL値は省かれる

In [25]:
# サンプル dframe
dframe1 = DataFrame(np.arange(8).reshape((2, 4)),
                 index=pd.Index(['LA', 'SF'], name='city'),
                 columns=pd.Index(['A', 'B', 'C','D'], name='letter'))
dframe1

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [28]:
# DataFrame -> Series
ser1 = dframe1.stack()
ser1

city  letter
LA    A         0
      B         1
      C         2
      D         3
SF    A         4
      B         5
      C         6
      D         7
dtype: int64

In [29]:
# Series -> DataFrame
ser1.unstack()

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7