# numpy 基本的な使い方

## インポート

いつものやつ

In [2]:
import numpy as np

## リストの作り方

こちらもいつものやつ。np.arrayを使うだけ

In [2]:
np_list = np.array([1,2,3,4])

In [3]:
np_list

array([1, 2, 3, 4])

## データの結合

リストと同様にくっつけて、np.arrayで定義すれば結合可能

In [4]:
my_list2 = [11,22,33,44]
my_lists = [np_list,my_list2]

In [5]:
my_lists

[array([1, 2, 3, 4]), [11, 22, 33, 44]]

In [6]:
np_lists = np.array(my_lists) #複数のリストをまとめるパターン

In [7]:
np_lists

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros(5).dtype #dtypeで型出力

dtype('float64')

## 単位行列

対角成分が1のやつ。np.eyeで作成できる

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 計算

通常の四則演算が可能 面倒だし説明は省略

In [12]:
5/2

2.5

In [13]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [14]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [15]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [17]:
arr1 ** 2

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [18]:
arr1 / 2

array([[0.5, 1. , 1.5, 2. ],
       [4. , 4.5, 5. , 5.5]])

In [19]:
arr1 + 1 #各要素の足し算になる（ブロードキャスト）

array([[ 2,  3,  4,  5],
       [ 9, 10, 11, 12]])

In [21]:
arr1 * 2

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

## 添え字アクセス
リストと同様なアクセスが可能。
python特有の機能として、=は参照なのに注意。
別変数として扱いたいのであれば、「copy()]メソッドを使うこと

In [3]:
arr = np.arange(1,11)

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[1:5] #添え字は0始まり

array([2, 3, 4, 5])

In [6]:
arr[0:4] = 100

In [7]:
arr

array([100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_arr = arr[0:6] #あくまでpythonは参照繋がりであることに注意。この場合、arr[0:6]に紐づかれる

In [15]:
slice_arr[:]= 999 # arr[0:6]に999を入れるのと同義となる

In [16]:
arr

array([999, 999, 999, 999, 999, 999,   6,   7,   8,   9,  10])

In [19]:
copy_arr = arr.copy() #こちらはコピー。元のarrとは繋がらない

In [20]:
copy_arr[:] = 55

In [21]:
arr

array([999, 999, 999, 999, 999, 999,   6,   7,   8,   9,  10])

In [22]:
# 2次元版
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [24]:
arr_2d[1] #0始まりなので、2行目が出力

array([20, 25, 30])

In [26]:
arr_2d[1,0] #2行目1列目

20

In [27]:
arr_2d[2,:] #3行目、列すべて

array([35, 40, 45])

In [34]:
arr_2d = np.zeros((10,20)) 

In [35]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [39]:
#次元が大きい順からaxisが割り当てられる 2次元ならshape[0]:axis=0(縦方向)で数えるので行数 、shape[1]:axis=1(横方向)で数えるので列数になる
print("行:",arr_2d.shape[0])
print("列:",arr_2d.shape[1])

for i in range(arr_2d.shape[0]): #shape[0]なので縦10で徹
    arr_2d[i] = i

列: 10
行: 20


In [38]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
        4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
        5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
        6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
        7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.,
        9., 9., 9., 9.]])

# 行列入れ替え

転置のやつ。.Tで出来る(transpose)

In [40]:
arr = np.arange(9).reshape(3,3)

In [45]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [44]:
arr.transpose(1,0) #行列の入れ替え axis=0とaxis=1を入れ替えてるだけなので、転置とやっていることは同じ

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])