# numpy 基本的な使い方

## インポート

いつものやつ

In [1]:
import numpy as np

## リストの作り方

こちらもいつものやつ。np.arrayを使うだけ

In [2]:
np_list = np.array([1,2,3,4])

In [3]:
np_list

array([1, 2, 3, 4])

## データの結合

リストと同様にくっつけて、np.arrayで定義すれば結合可能

In [4]:
my_list2 = [11,22,33,44]
my_lists = [np_list,my_list2]

In [5]:
my_lists

[array([1, 2, 3, 4]), [11, 22, 33, 44]]

In [6]:
np_lists = np.array(my_lists) #複数のリストをまとめるパターン

In [7]:
np_lists

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros(5).dtype #dtypeで型出力

dtype('float64')

## 単位行列

対角成分が1のやつ。np.eyeで作成できる

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 計算

通常の四則演算が可能 面倒だし説明は省略

In [12]:
5/2

2.5

In [13]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [14]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [15]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [17]:
arr1 ** 2

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [18]:
arr1 / 2

array([[0.5, 1. , 1.5, 2. ],
       [4. , 4.5, 5. , 5.5]])

In [19]:
arr1 + 1 #各要素の足し算になる（ブロードキャスト）

array([[ 2,  3,  4,  5],
       [ 9, 10, 11, 12]])

In [21]:
arr1 * 2

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])