# numpy 基本的な使い方

## インポート

いつものやつ

In [15]:
import numpy as np

## リストの作り方

こちらもいつものやつ。np.arrayを使うだけ

In [16]:
np_list = np.array([1,2,3,4])

In [17]:
np_list

array([1, 2, 3, 4])

## データの結合

リストと同様にくっつけて、np.arrayで定義すれば結合可能

In [18]:
my_list2 = [11,22,33,44]
my_lists = [np_list,my_list2]

In [19]:
my_lists

[array([1, 2, 3, 4]), [11, 22, 33, 44]]

In [20]:
np_lists = np.array(my_lists) #複数のリストをまとめるパターン

In [21]:
np_lists

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros(5).dtype #dtypeで型出力

dtype('float64')

## 単位行列

対角成分が1のやつ。np.eyeで作成できる

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# arry